out_path: D:\dev\upstageailab5-ml-regression-ml_r4\output
base_path: !!python/object/apply:pathlib.WindowsPath
- D:\
- dev
- upstageailab5-ml-regression-ml_r4
subway_feature: D:\dev\upstageailab5-ml-regression-ml_r4\data\subway_feature.csv
bus_feature: D:\dev\upstageailab5-ml-regression-ml_r4\data\bus_feature.csv
wandb:
  project: project-regression_house_price
  entity: joon
  group: group-ml4
target: price
thr_ratio_outlier: 0.01
thr_ratio_null: 0.9
time_delay: 3
random_seed: 2024
model_params:
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.01
data_paths:
  train: data/train.csv
  test: data/test.csv
features:
- feature1
- feature2
- feature3
sweep_configs:
  xgboost:
    method: bayes
    metric:
      name: rmse
      goal: minimize
    parameters:
      eta: 0.3
      max_depth: 10
      subsample: 0.6239
      colsample_bytree: 0.5305
      gamma: 4.717
      reg_lambda: 5.081
      alpha: 0.4902
      n_estimators: 551
  random_forest:
    method: bayes
    metric:
      name: rmse
      goal: minimize
    parameters:
      n_estimators: 200
      max_depth: 20
      min_samples_split: 2
      min_samples_leaf: 1
      max_features: log2
